name: Code coverage

on:
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@master
        with:
          node-version: 12

      - name: Install Dependencies
        run: npm i

      - name: Code coverage
        run: npm test
        env:
          SOLIDITY_COVERAGE: true

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

