name: Code coverage

on:
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 10.x
        uses: actions/setup-node@2.0.0
        with:
          node-version: 10.x

      - name: Install Dependencies
        run: npm ci

      - name: Code coverage
        run: npm test
        env:
          SOLIDITY_COVERAGE: true

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        
