name: Automated Linting and Unit Tests

on: [push, pull_request]

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Code Linting
        run: npm run lint

      - name: Unit tests
        run: npm test

      - name: Code coverage
        uses: coverallsapp/github-action@master
        run: npm test
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          SOLIDITY_COVERAGE: true
