name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 10.x
        uses: actions/setup-node@2.0.0
        with:
          node-version: 10.x

      - name: Install Dependencies
        run: npm ci

      - name: Code Linting
        run: npm run lint

      - name: Unit tests
        run: npm test        
